import { useCallback, useEffect, useState } from 'react';
import { Alert, Image, Pressable, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import { api, ApiError, authApi, uploadUrl } from '../../api';
import type { Attendance, DPR, Document, Expense, Material, Pagination, Project, Session, Task, Transaction, User, UserRole, Vendor } from '../../types';
import type { Section } from '../../navigation/sections';
import { roleName, rupees, statusTone } from '../../utils/formatters';
import { Button, Card, Empty, Field, Label, Page, Pill, Row, Sheet } from '../../ui';
import { appStyles as styles } from '../../theme/appStyles';

type Loadable<T> = { value: T; busy: boolean; error: string };
const pageData = <T,>(value: Pagination<T> | T[] | undefined) => Array.isArray(value) ? value : value?.data ?? [];
const errorText = (error: unknown) => error instanceof ApiError ? error.message : 'Something went wrong. Please retry.';
const can = (role: UserRole, roles: UserRole[]) => roles.includes(role);

function useLoader<T>(load: () => Promise<T>, initial: T, deps: unknown[] = []) {
  const [state, setState] = useState<Loadable<T>>({ value: initial, busy: true, error: '' });
  const refresh = useCallback(async () => { setState(current => ({ ...current, busy: true, error: '' })); try { const value = await load(); setState({ value, busy: false, error: '' }); } catch (error) { setState(current => ({ ...current, busy: false, error: errorText(error) })); } }, deps);
  useEffect(() => { void refresh(); }, [refresh]);
  return { ...state, refresh };
}
function ErrorCard({ message, retry }: { message: string; retry: () => void }) { return <Card><Text style={styles.error}>{message}</Text><Button label="Retry" onPress={retry} tone="outline" /></Card>; }
function Status({ value }: { value: string }) { return <Pill tone={statusTone(value)}>{value.replace(/-/g, ' ')}</Pill>; }
function FormSheet({ visible, title, onClose, children }: { visible: boolean; title: string; onClose: () => void; children: React.ReactNode }) { return <Sheet visible={visible} title={title} onClose={onClose}>{children}</Sheet>; }
function PickerButton({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={{ borderWidth: 1, borderColor: '#D9E1EE', borderRadius: 11, padding: 13, backgroundColor: '#F8FAFC' }}><Text style={{ color: '#2563EB', fontWeight: '700' }}>{label}</Text></Pressable>; }

export function HomeScreen({ role, onNavigate }: { role: UserRole; onNavigate: (section: Section) => void }) {
  const dashboard = useLoader(() => api.dashboard(), { kpis: {}, recentActivity: { pendingDprs: [], recentExpenses: [], activeProjectsList: [] } }, []);
  const mobile = useLoader(() => api.mobileDashboard(), {}, []);
  const kpis = { ...dashboard.value.kpis, ...mobile.value };
  return <Page title="BuildCorp" subtitle={`${roleName(role)} workspace`} refresh={dashboard.refresh} busy={dashboard.busy}>
    {dashboard.error ? <ErrorCard message={dashboard.error} retry={dashboard.refresh} /> : <>
      <View style={styles.kpiGrid}>{Object.entries(kpis).slice(0, 3).map(([key, value]) => <Card key={key} style={styles.kpi}><Text style={styles.kpiValue}>{typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value)}</Text><Text style={styles.kpiLabel}>{key.replace(/([A-Z])/g, ' $1')}</Text></Card>)}</View>
      <Card><Text style={styles.cardTitle}>Quick actions</Text><View style={styles.inlineButtons}><View style={{ flex: 1 }}><Button label="My tasks" onPress={() => onNavigate('tasks')} tone="outline" /></View><View style={{ flex: 1 }}><Button label="DPRs" onPress={() => onNavigate('dpr')} tone="outline" /></View></View></Card>
      <Text style={styles.sectionTitle}>Pending DPRs</Text>{dashboard.value.recentActivity.pendingDprs.length ? dashboard.value.recentActivity.pendingDprs.map(dpr => <Row key={dpr.id} title={dpr.siteName} detail={`${dpr.labourCount} labour · ${dpr.date?.slice(0, 10) ?? ''}`} badge={<Status value={dpr.status} />} />) : <Empty>No pending DPRs.</Empty>}
      <Text style={styles.sectionTitle}>Active projects</Text>{dashboard.value.recentActivity.activeProjectsList.map(project => <Row key={project.id} title={project.name} detail={`${project.location} · ${project.progress}% complete`} />)}
    </>}
  </Page>;
}

export function ProjectsScreen({ role = 'owner' }: { role?: UserRole }) {
  const list = useLoader(() => api.projects.list({ page: 1, limit: 40 }), { data: [], total: 0, page: 1, limit: 40, totalPages: 1 }, []);
  const [editing, setEditing] = useState<Project | null>(null); const [name, setName] = useState(''); const [location, setLocation] = useState(''); const [budget, setBudget] = useState(''); const [manager, setManager] = useState(''); const [startDate, setStartDate] = useState(''); const [endDate, setEndDate] = useState(''); const [saving, setSaving] = useState(false);
  const open = (project?: Project) => { setEditing(project ?? ({ id: 0 } as Project)); setName(project?.name ?? ''); setLocation(project?.location ?? ''); setBudget(project ? String(project.budget) : ''); setManager(project?.manager ?? ''); setStartDate(project?.startDate ?? ''); setEndDate(project?.endDate ?? ''); };
  const save = async () => { if (!name || !location || !budget || !manager || !startDate || !endDate) return Alert.alert('Required fields', 'Complete all project fields.'); setSaving(true); try { const data = { name, location, budget: Number(budget), manager, startDate, endDate }; editing?.id ? await api.projects.update(editing.id, data) : await api.projects.create(data); setEditing(null); await list.refresh(); } catch (error) { Alert.alert('Unable to save project', errorText(error)); } finally { setSaving(false); } };
  return <Page title="Projects" subtitle="Real project records" refresh={list.refresh} busy={list.busy}>{list.error ? <ErrorCard message={list.error} retry={list.refresh} /> : <>{can(role, ['owner', 'engineer']) && <Button label="Create project" onPress={() => open()} />}{pageData(list.value).map(project => <Pressable key={project.id} onPress={() => can(role, ['owner', 'engineer']) && open(project)}><Row title={project.name} detail={`${project.location} · ${project.manager} · ${project.progress}%`} badge={<Status value={project.status} />} /></Pressable>)}{!pageData(list.value).length && <Empty>No projects found.</Empty>}</>}<FormSheet visible={!!editing} title={editing?.id ? 'Edit project' : 'New project'} onClose={() => setEditing(null)}><Label>Name</Label><Field value={name} onChangeText={setName} placeholder="Project name" /><Label>Location</Label><Field value={location} onChangeText={setLocation} placeholder="Location" /><Label>Manager</Label><Field value={manager} onChangeText={setManager} placeholder="Manager" /><Label>Budget</Label><Field value={budget} onChangeText={setBudget} placeholder="Amount in rupees" keyboardType="numeric" /><Label>Start date</Label><Field value={startDate} onChangeText={setStartDate} placeholder="YYYY-MM-DD" /><Label>End date</Label><Field value={endDate} onChangeText={setEndDate} placeholder="YYYY-MM-DD" /><Button label={saving ? 'Saving…' : 'Save project'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function DprsScreen({ role }: { role: UserRole }) {
  const list = useLoader(() => api.dprs.list({ page: 1, limit: 40 }), { data: [], total: 0, page: 1, limit: 40, totalPages: 1 }, []);
  const [editing, setEditing] = useState<DPR | null>(null); const [siteName, setSiteName] = useState(''); const [labourCount, setLabourCount] = useState('0'); const [work, setWork] = useState(''); const [used, setUsed] = useState(''); const [wastage, setWastage] = useState('None'); const [notes, setNotes] = useState(''); const [images, setImages] = useState<ImagePicker.ImagePickerAsset[]>([]); const [bill, setBill] = useState<DocumentPicker.DocumentPickerAsset | null>(null); const [saving, setSaving] = useState(false);
  const open = (dpr?: DPR) => { setEditing(dpr ?? ({ id: 0 } as DPR)); setSiteName(dpr?.siteName ?? ''); setLabourCount(String(dpr?.labourCount ?? 0)); setWork(dpr?.workDescription ?? ''); setUsed(dpr?.materialUsed ?? ''); setWastage(dpr?.materialWastage ?? 'None'); setNotes(dpr?.notes ?? ''); setImages([]); setBill(null); };
  const chooseImages = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsMultipleSelection: true, selectionLimit: 5, quality: 0.75 }); if (!result.canceled) setImages(result.assets.slice(0, 5)); };
  const chooseBill = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ['image/*', 'application/pdf'], copyToCacheDirectory: true }); if (!result.canceled) setBill(result.assets[0]); };
  const save = async () => { if (!siteName || !work || !used || !wastage) return Alert.alert('Required fields', 'Complete the DPR details.'); setSaving(true); try { const form = new FormData(); [['siteName', siteName], ['labourCount', labourCount], ['workDescription', work], ['materialUsed', used], ['materialWastage', wastage], ['notes', notes]].forEach(([key, value]) => form.append(key, value)); images.forEach((image, index) => form.append('images', { uri: image.uri, name: image.fileName ?? `site-photo-${index}.jpg`, type: image.mimeType ?? 'image/jpeg' } as unknown as Blob)); if (bill) form.append('bill', { uri: bill.uri, name: bill.name, type: bill.mimeType ?? 'application/pdf' } as unknown as Blob); editing?.id ? await api.dprs.update(editing.id, form) : await api.dprs.create(form); setEditing(null); await list.refresh(); } catch (error) { Alert.alert('Unable to save DPR', errorText(error)); } finally { setSaving(false); } };
  return <Page title="Daily progress reports" subtitle="Site reports and evidence" refresh={list.refresh} busy={list.busy}>{list.error ? <ErrorCard message={list.error} retry={list.refresh} /> : <>{can(role, ['owner', 'engineer', 'supervisor']) && <Button label="Submit DPR" onPress={() => open()} />}{pageData(list.value).map(dpr => <Pressable key={dpr.id} onPress={() => can(role, ['owner', 'engineer', 'supervisor']) && open(dpr)}><Row title={dpr.siteName} detail={`${dpr.labourCount} labour · ${dpr.workDescription}`} badge={<Status value={dpr.status} />} /></Pressable>)}{!pageData(list.value).length && <Empty>No DPRs found.</Empty>}</>}<FormSheet visible={!!editing} title={editing?.id ? 'Edit DPR' : 'Submit DPR'} onClose={() => setEditing(null)}><Label>Site / block</Label><Field value={siteName} onChangeText={setSiteName} placeholder="Site section" /><Label>Labour count</Label><Field value={labourCount} onChangeText={setLabourCount} placeholder="0" keyboardType="numeric" /><Label>Work completed</Label><Field value={work} onChangeText={setWork} placeholder="Describe completed work" multiline /><Label>Materials used</Label><Field value={used} onChangeText={setUsed} placeholder="Materials and quantities" multiline /><Label>Material wastage</Label><Field value={wastage} onChangeText={setWastage} placeholder="Wastage details" multiline /><Label>Notes</Label><Field value={notes} onChangeText={setNotes} placeholder="Weather, issues, remarks" multiline /><PickerButton label={`Choose site photos (${images.length}/5)`} onPress={() => void chooseImages()} />{images.length ? <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{images.map(image => <Image key={image.uri} source={{ uri: image.uri }} style={{ width: 72, height: 72, borderRadius: 8 }} />)}</View> : null}<PickerButton label={bill ? `Bill: ${bill.name}` : 'Choose bill or receipt'} onPress={() => void chooseBill()} /><Button label={saving ? 'Submitting…' : 'Save DPR'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function TasksScreen({ role }: { role: UserRole }) {
  const list = useLoader(() => can(role, ['supervisor', 'engineer', 'labour']) ? api.tasks.mine() : api.tasks.list(), [], [role]);
  const [task, setTask] = useState<Task | null>(null); const [status, setStatus] = useState<Task['status']>('todo'); const [saving, setSaving] = useState(false);
  const update = async () => { if (!task) return; setSaving(true); try { await api.tasks.update(task.id, { status }); setTask(null); await list.refresh(); } catch (error) { Alert.alert('Unable to update task', errorText(error)); } finally { setSaving(false); } };
  return <Page title="Tasks" subtitle="Assigned work and progress" refresh={list.refresh} busy={list.busy}>{list.error ? <ErrorCard message={list.error} retry={list.refresh} /> : <>{list.value.map(item => <Pressable key={item.id} onPress={() => { setTask(item); setStatus(item.status); }}><Row title={item.title} detail={`${item.project ?? ''} · Due ${item.dueDate}`} badge={<Status value={item.status} />} /></Pressable>)}{!list.value.length && <Empty>No tasks found.</Empty>}</>}<FormSheet visible={!!task} title={task?.title ?? 'Task'} onClose={() => setTask(null)}><Text style={styles.muted}>{task?.description}</Text><Label>Status</Label>{(['todo', 'in-progress', 'review', 'done'] as const).map(value => <Button key={value} label={value} tone={status === value ? 'primary' : 'outline'} onPress={() => setStatus(value)} />)}<Button label={saving ? 'Updating…' : 'Update task'} onPress={update} disabled={saving} /></FormSheet></Page>;
}

export function AttendanceScreen({ role }: { role: UserRole }) {
  const list = useLoader(() => api.attendance.list(), [], []); const [sending, setSending] = useState(false);
  const act = async (action: 'check-in' | 'check-out') => { setSending(true); try { await api.attendance.mobile(action); await list.refresh(); } catch (error) { Alert.alert('Attendance update failed', errorText(error)); } finally { setSending(false); } };
  return <Page title="Attendance" subtitle="Live site attendance" refresh={list.refresh} busy={list.busy}>{list.error ? <ErrorCard message={list.error} retry={list.refresh} /> : <>{can(role, ['owner', 'supervisor', 'labour', 'engineer']) && <View style={styles.inlineButtons}><View style={{ flex: 1 }}><Button label={sending ? 'Working…' : 'Check in'} onPress={() => void act('check-in')} disabled={sending} /></View><View style={{ flex: 1 }}><Button label="Check out" tone="outline" onPress={() => void act('check-out')} disabled={sending} /></View></View>}{list.value.map(item => <Row key={item.id} title={item.name ?? `User ${item.userId}`} detail={`${item.date} · ${item.checkIn ?? '—'} to ${item.checkOut ?? '—'}`} badge={<Status value={item.status} />} />)}{!list.value.length && <Empty>No attendance records found.</Empty>}</>}</Page>;
}

export function StockScreen({ role = 'owner' }: { role?: UserRole }) {
  const materials = useLoader(() => api.materials.list({ page: 1, limit: 50 }), { data: [], total: 0, page: 1, limit: 50, totalPages: 1 }, []);
  const [form, setForm] = useState(false); const [name, setName] = useState(''); const [unit, setUnit] = useState(''); const [quantity, setQuantity] = useState(''); const [movement, setMovement] = useState<'in' | 'out'>('in'); const [saving, setSaving] = useState(false);
  const save = async () => { if (!name || !unit) return Alert.alert('Required fields', 'Material name and unit are required.'); setSaving(true); try { const material = await api.materials.create({ name, unit }); if (quantity) await api.materials.stock({ materialId: material.id, quantity: Number(quantity), type: movement, note: 'Added from mobile' }); setForm(false); setName(''); setUnit(''); setQuantity(''); await materials.refresh(); } catch (error) { Alert.alert('Unable to save material', errorText(error)); } finally { setSaving(false); } };
  return <Page title="Materials & stock" subtitle="Inventory and stock movement" refresh={materials.refresh} busy={materials.busy}>{materials.error ? <ErrorCard message={materials.error} retry={materials.refresh} /> : <>{can(role, ['owner', 'engineer']) && <Button label="Add material / opening stock" onPress={() => setForm(true)} />}{pageData(materials.value).map(material => { const quantity = (material.stocks ?? []).reduce((total, stock) => total + (stock.type === 'in' ? stock.quantity : -stock.quantity), 0); return <Row key={material.id} title={material.name} detail={`${quantity} ${material.unit} · ${material.category?.name ?? 'Uncategorised'}`} />; })}{!pageData(materials.value).length && <Empty>No materials found.</Empty>}</>}<FormSheet visible={form} title="Add material" onClose={() => setForm(false)}><Label>Material name</Label><Field value={name} onChangeText={setName} placeholder="e.g. Cement" /><Label>Unit</Label><Field value={unit} onChangeText={setUnit} placeholder="e.g. bags" /><Label>Opening quantity (optional)</Label><Field value={quantity} onChangeText={setQuantity} placeholder="0" keyboardType="numeric" /><View style={styles.inlineButtons}><View style={{ flex: 1 }}><Button label="Stock in" tone={movement === 'in' ? 'primary' : 'outline'} onPress={() => setMovement('in')} /></View><View style={{ flex: 1 }}><Button label="Stock out" tone={movement === 'out' ? 'primary' : 'outline'} onPress={() => setMovement('out')} /></View></View><Button label={saving ? 'Saving…' : 'Save material'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function CategoriesScreen({ role }: { role: UserRole }) {
  const categories = useLoader(() => api.categories.list({ page: 1, limit: 50 }), { data: [], total: 0, page: 1, limit: 50, totalPages: 1 }, []); const [show, setShow] = useState(false); const [name, setName] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { if (!name.trim()) return; setSaving(true); try { await api.categories.create(name.trim()); setName(''); setShow(false); await categories.refresh(); } catch (error) { Alert.alert('Unable to save category', errorText(error)); } finally { setSaving(false); } };
  if (!can(role, ['owner', 'engineer'])) return <Page title="Material categories"><Empty>Your role does not have access to categories.</Empty></Page>;
  return <Page title="Material categories" subtitle="Classify stock items" refresh={categories.refresh} busy={categories.busy}>{categories.error ? <ErrorCard message={categories.error} retry={categories.refresh} /> : <><Button label="Add category" onPress={() => setShow(true)} />{pageData(categories.value).map(category => <Row key={category.id} title={category.name} />)}{!pageData(categories.value).length && <Empty>No categories found.</Empty>}</>}<FormSheet visible={show} title="New category" onClose={() => setShow(false)}><Label>Category name</Label><Field value={name} onChangeText={setName} placeholder="e.g. Civil" /><Button label={saving ? 'Saving…' : 'Save category'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function VendorsScreen({ role }: { role: UserRole }) {
  const vendors = useLoader(() => api.vendors.list({ page: 1, limit: 50 }), { data: [], total: 0, page: 1, limit: 50, totalPages: 1 }, []); const [show, setShow] = useState(false); const [name, setName] = useState(''); const [contact, setContact] = useState(''); const [gstNumber, setGstNumber] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { if (!name || !contact) return Alert.alert('Required fields', 'Vendor name and contact are required.'); setSaving(true); try { await api.vendors.create({ name, contact, gstNumber }); setShow(false); setName(''); setContact(''); setGstNumber(''); await vendors.refresh(); } catch (error) { Alert.alert('Unable to save vendor', errorText(error)); } finally { setSaving(false); } };
  if (!can(role, ['owner', 'accountant'])) return <Page title="Vendors"><Empty>Your role does not have access to vendors.</Empty></Page>;
  return <Page title="Vendors" subtitle="Supplier contacts and GST details" refresh={vendors.refresh} busy={vendors.busy}>{vendors.error ? <ErrorCard message={vendors.error} retry={vendors.refresh} /> : <><Button label="Add vendor" onPress={() => setShow(true)} />{pageData(vendors.value).map(vendor => <Row key={vendor.id} title={vendor.name} detail={`${vendor.contact}${vendor.gstNumber ? ` · GST ${vendor.gstNumber}` : ''}`} />)}{!pageData(vendors.value).length && <Empty>No vendors found.</Empty>}</>}<FormSheet visible={show} title="New vendor" onClose={() => setShow(false)}><Label>Name</Label><Field value={name} onChangeText={setName} placeholder="Vendor name" /><Label>Contact</Label><Field value={contact} onChangeText={setContact} placeholder="Phone or email" /><Label>GST number</Label><Field value={gstNumber} onChangeText={setGstNumber} placeholder="Optional" /><Button label={saving ? 'Saving…' : 'Save vendor'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function FinanceScreen({ role = 'owner' }: { role?: UserRole }) {
  const transactions = useLoader(() => api.transactions.list({ page: 1, limit: 40 }), { data: [], total: 0, page: 1, limit: 40, totalPages: 1 }, []);
  const vendors = useLoader(() => api.vendors.list({ page: 1, limit: 50 }), { data: [], total: 0, page: 1, limit: 50, totalPages: 1 }, []);
  const [show, setShow] = useState(false); const [vendorId, setVendorId] = useState(''); const [amount, setAmount] = useState(''); const [type, setType] = useState<'credit' | 'debit'>('debit'); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { if (!vendorId || !amount) return Alert.alert('Required fields', 'Choose a vendor ID and enter an amount.'); setSaving(true); try { await api.transactions.create({ vendorId: Number(vendorId), amount: Number(amount), type, description }); setShow(false); await transactions.refresh(); } catch (error) { Alert.alert('Unable to save transaction', errorText(error)); } finally { setSaving(false); } };
  if (!can(role, ['owner', 'accountant'])) return <Page title="Finance"><Empty>Your role does not have access to finance records.</Empty></Page>;
  return <Page title="Owner ledger" subtitle="Vendor credits and debits" refresh={transactions.refresh} busy={transactions.busy}>{transactions.error ? <ErrorCard message={transactions.error} retry={transactions.refresh} /> : <><Button label="Add transaction" onPress={() => setShow(true)} />{pageData(transactions.value).map(transaction => <Row key={transaction.id} title={`${transaction.type === 'credit' ? '+' : '−'} ${rupees(transaction.amount)}`} detail={`${transaction.vendor?.name ?? `Vendor ${transaction.vendorId}`} · ${transaction.description ?? 'No description'}`} badge={<Status value={transaction.type} />} />)}{!pageData(transactions.value).length && <Empty>No transactions found.</Empty>}</>}<FormSheet visible={show} title="New transaction" onClose={() => setShow(false)}><Text style={styles.muted}>Choose a vendor ID from the list: {pageData(vendors.value).map(vendor => `${vendor.id}: ${vendor.name}`).join(', ') || 'no vendors available'}.</Text><Label>Vendor ID</Label><Field value={vendorId} onChangeText={setVendorId} placeholder="Vendor ID" keyboardType="numeric" /><Label>Amount</Label><Field value={amount} onChangeText={setAmount} placeholder="Amount in rupees" keyboardType="numeric" /><View style={styles.inlineButtons}><View style={{ flex: 1 }}><Button label="Debit" tone={type === 'debit' ? 'primary' : 'outline'} onPress={() => setType('debit')} /></View><View style={{ flex: 1 }}><Button label="Credit" tone={type === 'credit' ? 'primary' : 'outline'} onPress={() => setType('credit')} /></View></View><Label>Description</Label><Field value={description} onChangeText={setDescription} placeholder="Reference or remarks" multiline /><Button label={saving ? 'Saving…' : 'Save transaction'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function PeopleScreen({ role = 'owner' }: { role?: UserRole }) {
  const employees = useLoader(() => api.employees.list({ page: 1, limit: 50 }), { data: [], total: 0, page: 1, limit: 50, totalPages: 1 }, []);
  const [show, setShow] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [employeeRole, setEmployeeRole] = useState<UserRole>('labour'); const [saving, setSaving] = useState(false);
  const save = async () => { if (!name || !email) return Alert.alert('Required fields', 'Name and email are required.'); setSaving(true); try { await api.employees.create({ name, email, phone, role: employeeRole }); setShow(false); await employees.refresh(); } catch (error) { Alert.alert('Unable to save employee', errorText(error)); } finally { setSaving(false); } };
  if (role !== 'owner') return <Page title="People"><Empty>Only owners can manage employees.</Empty></Page>;
  return <Page title="Employees" subtitle="People and workforce" refresh={employees.refresh} busy={employees.busy}>{employees.error ? <ErrorCard message={employees.error} retry={employees.refresh} /> : <><Button label="Add employee" onPress={() => setShow(true)} />{pageData(employees.value).map(employee => <Row key={employee.id} title={employee.name} detail={`${employee.email} · ${employee.phone ?? 'No phone'}`} badge={<Status value={employee.role} />} />)}{!pageData(employees.value).length && <Empty>No employees found.</Empty>}</>}<FormSheet visible={show} title="New employee" onClose={() => setShow(false)}><Label>Name</Label><Field value={name} onChangeText={setName} placeholder="Full name" /><Label>Email</Label><Field value={email} onChangeText={setEmail} placeholder="Email address" keyboardType="email-address" /><Label>Phone</Label><Field value={phone} onChangeText={setPhone} placeholder="Phone number" /><Label>Role</Label>{(['owner', 'engineer', 'supervisor', 'accountant', 'labour'] as UserRole[]).map(value => <Button key={value} label={roleName(value)} tone={employeeRole === value ? 'primary' : 'outline'} onPress={() => setEmployeeRole(value)} />)}<Button label={saving ? 'Saving…' : 'Save employee'} onPress={save} disabled={saving} /></FormSheet></Page>;
}

export function DocumentsScreen() {
  const docs = useLoader(() => api.documents.list(), [], []); const [uploading, setUploading] = useState(false);
  const upload = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ['image/*', 'application/pdf'], copyToCacheDirectory: true }); if (result.canceled) return; setUploading(true); try { const file = result.assets[0]; const form = new FormData(); form.append('file', { uri: file.uri, name: file.name, type: file.mimeType ?? 'application/octet-stream' } as unknown as Blob); form.append('folder', 'General'); await api.documents.create(form); await docs.refresh(); } catch (error) { Alert.alert('Upload failed', errorText(error)); } finally { setUploading(false); } };
  return <Page title="Documents" subtitle="Images and PDFs" refresh={docs.refresh} busy={docs.busy}>{docs.error ? <ErrorCard message={docs.error} retry={docs.refresh} /> : <><Button label={uploading ? 'Uploading…' : 'Upload document'} onPress={() => void upload()} disabled={uploading} />{docs.value.map(document => <Pressable key={document.id} onPress={() => document.filename && Alert.alert(document.name, uploadUrl(document.filename))}><Row title={document.name} detail={`${document.type} · ${document.size} · ${document.folder}`} /></Pressable>)}{!docs.value.length && <Empty>No documents found.</Empty>}</>}</Page>;
}

export function AuditScreen({ role = 'owner' }: { role?: UserRole }) { const audit = useLoader(() => api.audit.list({ page: 1, limit: 50 }), { data: [], total: 0, page: 1, limit: 50, totalPages: 1 }, []); if (role !== 'owner') return <Page title="Audit log"><Empty>Only owners can access audit logs.</Empty></Page>; return <Page title="Audit log" subtitle="Accountable system history" refresh={audit.refresh} busy={audit.busy}>{audit.error ? <ErrorCard message={audit.error} retry={audit.refresh} /> : <>{pageData(audit.value).map(item => <Row key={item.id} title={`${item.module}: ${item.action}`} detail={`Record ${item.recordId} · ${item.createdAt}`} badge={item.role ? <Status value={item.role} /> : undefined} />)}{!pageData(audit.value).length && <Empty>No audit records found.</Empty>}</>}</Page>; }

export function ProfileScreen({ user, onLogout }: { user: User; onLogout: () => Promise<void> }) {
  const [name, setName] = useState(user.name); const [phone, setPhone] = useState(user.phone ?? ''); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); try { await authApi.profile({ name, phone }); Alert.alert('Profile updated', 'Your details have been saved.'); } catch (error) { Alert.alert('Unable to update profile', errorText(error)); } finally { setSaving(false); } };
  const allDevices = async () => { try { await authApi.logoutAll(); await onLogout(); } catch (error) { Alert.alert('Unable to sign out all devices', errorText(error)); } };
  return <Page title="Profile" subtitle={`${roleName(user.role)} account`}><Card style={styles.profileCard}><View style={styles.largeAvatar}><Text style={styles.largeAvatarText}>{user.name.split(' ').map(part => part[0]).slice(0, 2).join('')}</Text></View><Text style={styles.profileName}>{user.name}</Text><Text style={styles.muted}>{user.email}</Text></Card><Label>Name</Label><Field value={name} onChangeText={setName} placeholder="Your name" /><Label>Phone</Label><Field value={phone} onChangeText={setPhone} placeholder="Phone number" keyboardType="numeric" /><Button label={saving ? 'Saving…' : 'Save profile'} onPress={save} disabled={saving} /><Button label="Sign out" onPress={() => void onLogout()} tone="danger" /><Button label="Sign out all devices" onPress={() => void allDevices()} tone="outline" /></Page>;
}
