import { StyleSheet } from 'react-native';
import { colors } from '../ui';

export const appStyles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bg, gap: 8 },
  brand: { color: colors.navy, fontSize: 30, fontWeight: '900' },
  muted: { color: colors.slate },
  login: { flex: 1, backgroundColor: colors.bg, padding: 24, justifyContent: 'center', alignItems: 'center', gap: 11 },
  logo: { width: 64, height: 64, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue },
  logoText: { color: '#fff', fontSize: 33, fontWeight: '900' },
  tagline: { color: colors.slate, marginBottom: 18 },
  endpoint: { color: '#94A3B8', fontSize: 11, textAlign: 'center', marginTop: 8 },
  error: { color: colors.red, fontWeight: '700', fontSize: 13 },
  topbar: { backgroundColor: colors.surface, paddingHorizontal: 20, paddingVertical: 13, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  topbarName: { color: colors.navy, fontSize: 15, fontWeight: '800' },
  topbarRole: { color: colors.slate, fontSize: 12, marginTop: 2 },
  avatar: { height: 39, width: 39, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.sky },
  avatarText: { color: colors.blue, fontWeight: '900' },
  nav: { maxHeight: 76, backgroundColor: colors.surface, borderTopColor: colors.border, borderTopWidth: 1 },
  navItems: { paddingHorizontal: 10, alignItems: 'center', gap: 6 },
  navItem: { minWidth: 62, paddingHorizontal: 9, paddingVertical: 9, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  navActive: { backgroundColor: colors.sky },
  navIcon: { color: colors.slate, fontSize: 18, height: 21 },
  navLabel: { color: colors.slate, fontSize: 10, fontWeight: '700', marginTop: 2 },
  navLabelActive: { color: colors.blue },
  kpiGrid: { flexDirection: 'row', gap: 8 },
  kpi: { flex: 1, padding: 12 },
  kpiValue: { color: colors.navy, fontSize: 23, fontWeight: '900' },
  kpiLabel: { color: colors.slate, fontSize: 10, textTransform: 'capitalize', marginTop: 4 },
  cardTitle: { color: colors.navy, fontSize: 16, fontWeight: '800', marginBottom: 8 },
  metric: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 9, borderBottomColor: '#EEF2F7', borderBottomWidth: 1 },
  metricValue: { color: colors.navy, fontWeight: '800' },
  sectionTitle: { color: colors.navy, fontSize: 16, fontWeight: '800', marginTop: 8 },
  quick: { gap: 8 },
  inlineButtons: { flexDirection: 'row', gap: 8 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  rowTitle: { color: colors.navy, fontSize: 15, fontWeight: '800' },
  progressTrack: { height: 7, borderRadius: 9, backgroundColor: '#E2E8F0', marginVertical: 12, overflow: 'hidden' },
  progress: { height: 7, backgroundColor: colors.blue, borderRadius: 9 },
  money: { color: colors.green, fontWeight: '900', fontSize: 14 },
  profileCard: { alignItems: 'center', gap: 7, paddingVertical: 24 },
  largeAvatar: { width: 74, height: 74, borderRadius: 37, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.sky },
  largeAvatarText: { color: colors.blue, fontSize: 25, fontWeight: '900' },
  profileName: { color: colors.navy, fontSize: 20, fontWeight: '900' },
});
