import type { ReactNode } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export const colors = { navy: '#10233F', blue: '#2563EB', sky: '#E8F0FF', green: '#16803C', amber: '#B45309', red: '#C2410C', slate: '#64748B', border: '#D9E1EE', surface: '#FFFFFF', bg: '#F6F8FC' };

export function Page({ title, subtitle, children, refresh, busy = false }: { title: string; subtitle?: string; children: ReactNode; refresh?: () => void; busy?: boolean }) {
  return <ScrollView style={styles.page} contentContainerStyle={styles.pageContent} showsVerticalScrollIndicator={false}>
    <View style={styles.heading}><View style={{ flex: 1 }}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{refresh ? <Pressable onPress={refresh} style={styles.iconButton}><Text>↻</Text></Pressable> : null}</View>
    {busy ? <View style={styles.loader}><ActivityIndicator color={colors.blue} /><Text style={styles.muted}>Loading live data…</Text></View> : children}
  </ScrollView>;
}

export function Card({ children, style }: { children: ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Label({ children }: { children: ReactNode }) { return <Text style={styles.label}>{children}</Text>; }
export function Field({ value, onChangeText, placeholder, multiline = false, keyboardType = 'default', secureTextEntry = false }: { value: string; onChangeText: (v: string) => void; placeholder: string; multiline?: boolean; keyboardType?: 'default' | 'numeric' | 'email-address'; secureTextEntry?: boolean }) { return <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#94A3B8" keyboardType={keyboardType} secureTextEntry={secureTextEntry} multiline={multiline} style={[styles.input, multiline && styles.textarea]} />; }
export function Button({ label, onPress, tone = 'primary', disabled = false }: { label: string; onPress: () => void; tone?: 'primary' | 'outline' | 'danger'; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, tone === 'outline' && styles.outline, tone === 'danger' && styles.danger, disabled && styles.disabled]}><Text style={[styles.buttonText, tone === 'outline' && styles.outlineText]}>{label}</Text></Pressable>; }
export function Pill({ children, tone = 'blue' }: { children: ReactNode; tone?: 'blue' | 'green' | 'amber' | 'red' | 'slate' }) { return <View style={[styles.pill, tone === 'green' && styles.greenPill, tone === 'amber' && styles.amberPill, tone === 'red' && styles.redPill, tone === 'slate' && styles.slatePill]}><Text style={[styles.pillText, tone === 'green' && styles.greenText, tone === 'amber' && styles.amberText, tone === 'red' && styles.redText]}>{children}</Text></View>; }
export function Empty({ children = 'No records found.' }: { children?: ReactNode }) { return <Card><Text style={styles.empty}>{children}</Text></Card>; }
export function Row({ title, detail, badge, children }: { title: string; detail?: string; badge?: ReactNode; children?: ReactNode }) { return <Card><View style={styles.row}><View style={{ flex: 1, gap: 4 }}><Text style={styles.rowTitle}>{title}</Text>{detail ? <Text style={styles.muted}>{detail}</Text> : null}</View>{badge || children}</View></Card>; }
export function Sheet({ visible, title, children, onClose }: { visible: boolean; title: string; children: ReactNode; onClose: () => void }) { return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{title}</Text><Pressable onPress={onClose}><Text style={styles.close}>Close</Text></Pressable></View><ScrollView contentContainerStyle={styles.form}>{children}</ScrollView></View></Modal>; }

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg }, pageContent: { padding: 20, paddingBottom: 112, gap: 12 }, heading: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 }, title: { color: colors.navy, fontSize: 26, fontWeight: '800' }, subtitle: { color: colors.slate, marginTop: 4, fontSize: 13 }, iconButton: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface }, loader: { height: 260, alignItems: 'center', justifyContent: 'center', gap: 12 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 15, shadowColor: '#0F172A', shadowOpacity: 0.03, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 1 }, label: { color: colors.navy, fontSize: 13, fontWeight: '700', marginTop: 5 }, input: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: colors.border, color: colors.navy, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 11, fontSize: 15 }, textarea: { minHeight: 96, textAlignVertical: 'top' }, button: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue, borderRadius: 11, paddingVertical: 13, paddingHorizontal: 15, marginTop: 5 }, buttonText: { color: '#FFF', fontWeight: '800', fontSize: 14 }, outline: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.blue }, outlineText: { color: colors.blue }, danger: { backgroundColor: colors.red }, disabled: { opacity: .55 }, pill: { backgroundColor: colors.sky, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999 }, pillText: { color: colors.blue, fontWeight: '800', fontSize: 11, textTransform: 'capitalize' }, greenPill: { backgroundColor: '#DCFCE7' }, greenText: { color: colors.green }, amberPill: { backgroundColor: '#FEF3C7' }, amberText: { color: colors.amber }, redPill: { backgroundColor: '#FFEDD5' }, redText: { color: colors.red }, slatePill: { backgroundColor: '#E2E8F0' }, row: { flexDirection: 'row', alignItems: 'center', gap: 10 }, rowTitle: { color: colors.navy, fontSize: 15, fontWeight: '800' }, muted: { color: colors.slate, fontSize: 12, lineHeight: 18 }, empty: { color: colors.slate, textAlign: 'center', paddingVertical: 18 }, sheet: { flex: 1, backgroundColor: colors.bg }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomColor: colors.border, borderBottomWidth: 1, backgroundColor: colors.surface }, sheetTitle: { color: colors.navy, fontSize: 19, fontWeight: '800' }, close: { color: colors.blue, fontWeight: '800' }, form: { padding: 20, gap: 10, paddingBottom: 52 },
});
